__constructor__: build_policy_net
vocab: 13  # i.e) 12 pieces + empty square
embedding_dim: 512
hidden_dim: 512
nb_layers: 6
nb_heads: 8
head_dim: 64
output_dim: 4096
dropout: 0.1
separate_rank_and_file: true